### ISSUE TITLE
Game:create_character issues

### ISSUE THREAD

**Issue by seiyria** [LandOfTheRair/core2#11]
it:
-  [ ] should set baseclass to Undecided if baseClass is anything other than Mage, Warrior, Thief, Healer (players are not required to choose a class)
- [ ] should only initialize the core stats (str, dex, con, int, agi, wil, cha, luk, wis) to a base of 10 (more/less depending on choices in char create).
- [ ] hpregen should be 1
- [ ] mpregen should be 0 (unless you're a magic class, then it's 1 - this is changed if you dedicate to a class in game as well)
- [ ] hp should be derived from the YML with a base of 100 (more/less depending on choices in char create)
- [ ] mp should be 0 (unless you're a magic class, then it's 30 - similar to above)
- [ ] actionSpeed should be set to 1.
- [ ] should validate that the name has no spaces, numbers, and the first letter is uppercase
- [ ] set level to 1
- [ ] set map to Tutorial
- [ ] set x/y to 14, 14

it should not:
- [ ] validate a player with that name already exists (I get this error when creating a char with the same name)

the char create response should:

- [ ] not include stats
- [ ] include name, class (or undecided), level, char slot, current map

the login response should:

- [ ] include players (currently it does not populate the array)

**Comment by Oipo** [comment]
Marking things that should be fixed.

it:
-  [ ] should set baseclass to Undecided if baseClass is anything other than Mage, Warrior, Thief, Healer (players are not required to choose a class)
- [ ] should only initialize the core stats (str, dex, con, int, agi, wil, cha, luk, wis) to a base of 10 (more/less depending on choices in char create).
- [ ] hpregen should be 1
- [ ] mpregen should be 0 (unless you're a magic class, then it's 1 - this is changed if you dedicate to a class in game as well)
- [ ] hp should be derived from the YML with a base of 100 (more/less depending on choices in char create)
- [ ] mp should be 0 (unless you're a magic class, then it's 30 - similar to above)
- [ ] actionSpeed should be set to 1.
- [ ] should validate that the name has no spaces, numbers, and the first letter is uppercase
- [ ] set level to 1
- [ ] set map to Tutorial
- [ ] set x/y to 14, 14

it should not:
- [x] ~~validate a player with that name already exists (I get this error when creating a char with the same name)~~ it now properly checks if a slot has already been used or not. Delete a slot before creating a new one.

the char create response should:

- [ ] ~~not include stats~~ should include stats because the definitions of the allegiance/class stuff is in yml files on the server.
- [ ] include name, class (or undecided), level, char slot, current map

the login response should:

- [x] ~~include players (currently it does not populate the array)~~

**Comment by Oipo** [comment]
I believe that this issue can be closed. If not, feel free to re-open or create new issues.
